version: "3"

services:
  mysql:
    image: mariadb
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress

  wordpress:
    image: "wordpress:${WP_VERSION-}php${PHP_VERSION:-7.2}"
    ports:
      - "8080:80"
    volumes:
      -  "./:/var/www/html/wp-content/plugins/${PLUGIN_NAME:-clover}"
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
